name: GH-ACTION-DOCKER-COMPOSE-BUILD-IMAGE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  GH-ACTION-DOCKER-COMPOSE-BUILD-IMAGE:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: GH-ACTION-DOCKER-COMPOSE-BUILD
        uses: TheKitoInc/gh-action-docker-compose-build@main
